/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school;

import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.EventQueue;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tharaka Rumesh Jee
 */
public class assignment extends javax.swing.JInternalFrame {
    Connection con= null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    ArrayList name = new ArrayList();
    ArrayList names = new ArrayList();
    ArrayList name1 = new ArrayList();
    ArrayList names1 = new ArrayList();
    
    /**
     * Creates new form assignment
     */
    public assignment() {
        initComponents();
        con = db.connect();
        databaseNama();
        databaseNamas();
        databaseNama1();
        databaseNamas1();
        table();
        items();
        search.setEnabled(false);
        jButton2.setVisible(false);
        jButton1.setVisible(true);
        jButton3.setEnabled(false);
    }

     public void items(){
        TextAutoCompleter textAutocompleter = new TextAutoCompleter(txtsearch);
        
          String sq2 = "SELECT st_fullname FROM student_all";
            
        try{
            pst = con.prepareStatement(sq2);
            rs = pst.executeQuery();
                
            while(rs.next()){
//                String a1 = rs.getString("st_fullname");
//                String a2 = rs.getString("st_grade");
//                String a3 = rs.getString("st_class");
//                String a4 = a1 + " " + a2 + "-" + a3;
                textAutocompleter.addItem(rs.getString("st_fullname"));
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setPreferredSize(new java.awt.Dimension(1073, 612));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Assessment Marks");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        jLabel2.setText("Name");

        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsearchKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsearchKeyTyped(evt);
            }
        });

        search.setBackground(new java.awt.Color(0, 51, 51));
        search.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search))
                .addGap(11, 11, 11))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        jLabel3.setText("Grade");

        jLabel4.setText("Class");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "please select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "please select", "A", "B", "C" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Index  No");

        jLabel6.setText("Last Name");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });

        jLabel11.setText("First  Name");

        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 51, 51));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Serach");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                .addGap(122, 122, 122)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(jTextField2))
                .addGap(113, 113, 113)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, 155, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(9, 9, 9))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        jLabel7.setText("Assessment Number");

        jLabel8.setText("Marks");

        jLabel9.setText("Assessment Name");

        jLabel10.setText("Description");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "please select", "1", "2", "3", "4", "5", "6" }));

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox3, 0, 185, Short.MAX_VALUE)
                    .addComponent(jTextField5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(114, 114, 114)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        jButton1.setBackground(new java.awt.Color(0, 51, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Save Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 153, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update Details");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(11, 11, 11))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Index", "Last Name", "Grade", "Class", "As. Name", "As. 1 ", "As. Name", "As. 2", "As. Name", "As. 3", "As. Name", "As. 4", "As. Name", "As. 5", "As. Name", "As. 6"
            }
        ));
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable2.setSurrendersFocusOnKeystroke(true);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

         if(jComboBox1.getSelectedItem()=="please select" || jComboBox2.getSelectedItem()=="please select" || jComboBox3.getSelectedItem()=="please select") {
           JOptionPane.showMessageDialog(null, "please enter or select correct values");
       }

         else {
        if(jComboBox3.getSelectedItem()=="1"){
         try {
                 
                String sql = "UPDATE student_all set st_as_1='" + jComboBox3.getSelectedItem() + "',st_as_name1='" + jTextField5.getText() + "',st_as_marks1='" + jTextField3.getText() + "',st_as_desc1='" + jTextField4.getText()  +  "' WHERE st_fullname='" + txtsearch.getText() + "' AND st_grade = '"+jComboBox1.getSelectedItem()+"' AND st_class = '"+jComboBox2.getSelectedItem()+"' ";
                pst = con.prepareStatement(sql);
                pst.execute();
                
                JOptionPane.showMessageDialog(null, "Added Successfully");
              
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Adding Failed");
            }
        }

        else if(jComboBox3.getSelectedItem()=="2"){
         try {
                 
                String sql = "UPDATE student_all set st_as_2='" + jComboBox3.getSelectedItem() + "',st_as_name2='" + jTextField5.getText() + "',st_as_marks2='" + jTextField3.getText() + "',st_as_desc2='" + jTextField4.getText()  +  "' WHERE st_fullname='" + txtsearch.getText() + "' AND st_grade = '"+jComboBox1.getSelectedItem()+"' AND st_class = '"+jComboBox2.getSelectedItem()+"' ";
                pst = con.prepareStatement(sql);
                pst.execute();
                
                JOptionPane.showMessageDialog(null, "Added Successfully");
              
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Adding Failed");
            }
        }
        
        else if(jComboBox3.getSelectedItem()=="3"){
         try {
                 
                String sql = "UPDATE student_all set st_as_3='" + jComboBox3.getSelectedItem() + "',st_as_name3='" + jTextField5.getText() + "',st_as_marks3='" + jTextField3.getText() + "',st_as_desc3='" + jTextField4.getText()  +  "' WHERE st_fullname='" + txtsearch.getText() + "' AND st_grade = '"+jComboBox1.getSelectedItem()+"' AND st_class = '"+jComboBox2.getSelectedItem()+"' ";
                pst = con.prepareStatement(sql);
                pst.execute();
                
                JOptionPane.showMessageDialog(null, "Added Successfully");
              
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Adding Failed");
            }
        }
         
        else if(jComboBox3.getSelectedItem()=="4"){
         try {
                 
                String sql = "UPDATE student_all set st_as_4='" + jComboBox3.getSelectedItem() + "',st_as_name4='" + jTextField5.getText() + "',st_as_marks4='" + jTextField3.getText() + "',st_as_desc4='" + jTextField4.getText()  +  "' WHERE st_fullname='" + txtsearch.getText() + "' AND st_grade = '"+jComboBox1.getSelectedItem()+"' AND st_class = '"+jComboBox2.getSelectedItem()+"' ";
                pst = con.prepareStatement(sql);
                pst.execute();
                
                JOptionPane.showMessageDialog(null, "Added Successfully");
              
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Adding Failed");
            }
        }
        
        else if(jComboBox3.getSelectedItem()=="5"){
         try {
                 
                String sql = "UPDATE student_all set st_as_5='" + jComboBox3.getSelectedItem() + "',st_as_name5='" + jTextField5.getText() + "',st_as_marks5='" + jTextField3.getText() + "',st_as_desc5='" + jTextField4.getText()  +  "' WHERE st_fullname='" + txtsearch.getText() + "' AND st_grade = '"+jComboBox1.getSelectedItem()+"' AND st_class = '"+jComboBox2.getSelectedItem()+"' ";
                pst = con.prepareStatement(sql);
                pst.execute();
                
                JOptionPane.showMessageDialog(null, "Added Successfully");
              
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Adding Failed");
            }
        }
        
        else if(jComboBox3.getSelectedItem()=="6"){
         try {
                 
                String sql = "UPDATE student_all set st_as_6='" + jComboBox3.getSelectedItem() + "',st_as_name6='" + jTextField5.getText() + "',st_as_marks6='" + jTextField3.getText() + "',st_as_desc6='" + jTextField4.getText()  +  "' WHERE st_fullname='" + txtsearch.getText() + "' AND st_grade = '"+jComboBox1.getSelectedItem()+"' AND st_class = '"+jComboBox2.getSelectedItem()+"' ";
                pst = con.prepareStatement(sql);
                pst.execute();
                
                JOptionPane.showMessageDialog(null, "Added Successfully");
              
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Adding Failed");
            }
        }
        
        else {
             JOptionPane.showMessageDialog(null, "Please Select Correct Assessment Number");
        }
         table();
        databaseNama();
        databaseNamas();
        databaseNama1();
        databaseNamas1();
         reset();
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        try {
            
             Connection conn = db.connect();
               Statement s = conn.createStatement();
             
            rs = s.executeQuery("SELECT * FROM student_all WHERE st_fullname='" + txtsearch.getText() + "'");
            while (rs.next()) {

                jTextField1.setText(rs.getString("st_fname"));
                jTextField6.setText(rs.getString("st_mname"));
                jTextField2.setText(rs.getString("st_lname"));
                jComboBox1.setSelectedItem(rs.getString("st_grade"));
                jComboBox2.setSelectedItem(rs.getString("st_class"));
                
         }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Name");
            
        }        
                
    }//GEN-LAST:event_searchActionPerformed

    public void table() {

        DefaultTableModel dtf = (DefaultTableModel) jTable2.getModel();
        dtf.setRowCount(0);

        try {
                Connection conn = db.connect();
                Statement s = conn.createStatement();
            
            rs=s.executeQuery("SELECT * FROM student_all ORDER BY st_grade,st_class,st_fname,st_mname,st_lname,st_as_marks1,st_as_marks2,st_as_marks3,st_as_marks4,st_as_marks5,st_as_marks6 ASC");

            while (rs.next()) {

                Vector v = new Vector();

                v.add(rs.getString("st_fname"));
                v.add(rs.getString("st_lname"));
                v.add(rs.getString("st_grade"));
                v.add(rs.getString("st_class"));
                v.add(rs.getString("st_as_name1"));
                v.add(rs.getString("st_as_marks1"));
                v.add(rs.getString("st_as_name2"));
                v.add(rs.getString("st_as_marks2"));
                v.add(rs.getString("st_as_name3"));
                v.add(rs.getString("st_as_marks3"));
                v.add(rs.getString("st_as_name4"));
                v.add(rs.getString("st_as_marks4"));
                v.add(rs.getString("st_as_name5"));
                v.add(rs.getString("st_as_marks5"));
                v.add(rs.getString("st_as_name6"));
                v.add(rs.getString("st_as_marks6"));
            
                dtf.addRow(v);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Table load Fail");
        }
    }
    
    public void reset() {
        jTextField3.setText("");
        jTextField2.setText("");
        jTextField1.setText("");
        txtsearch.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jComboBox3.setSelectedIndex(0);
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);      
    }
    
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          if(jComboBox1.getSelectedItem()=="please select" || jComboBox2.getSelectedItem()=="please select" || jComboBox3.getSelectedItem()=="please select") {
           JOptionPane.showMessageDialog(null, "please enter or select correct values");
       }

         else {
        
        if(jComboBox3.getSelectedItem()=="1"){
         try {
                 
                String sql = "UPDATE student_all set st_as_1='" + jComboBox3.getSelectedItem() + "',st_as_name1='" + jTextField5.getText() + "',st_as_marks1='" + jTextField3.getText() + "',st_as_desc1='" + jTextField4.getText()  +  "' WHERE st_fullname='" + txtsearch.getText() + "' AND st_grade = '"+jComboBox1.getSelectedItem()+"' AND st_class = '"+jComboBox2.getSelectedItem()+"' ";
                pst = con.prepareStatement(sql);
                pst.execute();
                
                JOptionPane.showMessageDialog(null, "Added Successfully");
              
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Adding Failed");
            }
        }

        else if(jComboBox3.getSelectedItem()=="2"){
         try {
                 
                String sql = "UPDATE student_all set st_as_2='" + jComboBox3.getSelectedItem() + "',st_as_name2='" + jTextField5.getText() + "',st_as_marks2='" + jTextField3.getText() + "',st_as_desc2='" + jTextField4.getText()  +  "' WHERE st_fullname='" + txtsearch.getText() + "' AND st_grade = '"+jComboBox1.getSelectedItem()+"' AND st_class = '"+jComboBox2.getSelectedItem()+"' ";
                pst = con.prepareStatement(sql);
                pst.execute();
                
                JOptionPane.showMessageDialog(null, "Added Successfully");
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Adding Failed");
            }
        }
        
        else if(jComboBox3.getSelectedItem()=="3"){
         try {
                 
                String sql = "UPDATE student_all set st_as_3='" + jComboBox3.getSelectedItem() + "',st_as_name3='" + jTextField5.getText() + "',st_as_marks3='" + jTextField3.getText() + "',st_as_desc3='" + jTextField4.getText()  +  "' WHERE st_fullname='" + txtsearch.getText() + "' AND st_grade = '"+jComboBox1.getSelectedItem()+"' AND st_class = '"+jComboBox2.getSelectedItem()+"' ";
                pst = con.prepareStatement(sql);
                pst.execute();
                
                JOptionPane.showMessageDialog(null, "Added Successfully");
              
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Adding Failed");
            }
        }
         
        else if(jComboBox3.getSelectedItem()=="4"){
         try {
                 
                String sql = "UPDATE student_all set st_as_4='" + jComboBox3.getSelectedItem() + "',st_as_name4='" + jTextField5.getText() + "',st_as_marks4='" + jTextField3.getText() + "',st_as_desc4='" + jTextField4.getText()  +  "' WHERE st_fullname='" + txtsearch.getText() + "' AND st_grade = '"+jComboBox1.getSelectedItem()+"' AND st_class = '"+jComboBox2.getSelectedItem()+"' ";
                pst = con.prepareStatement(sql);
                pst.execute();
                
                JOptionPane.showMessageDialog(null, "Added Successfully");
              
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Adding Failed");
            }
        }
        
        else if(jComboBox3.getSelectedItem()=="5"){
         try {
                 
                String sql = "UPDATE student_all set st_as_5='" + jComboBox3.getSelectedItem() + "',st_as_name5='" + jTextField5.getText() + "',st_as_marks5='" + jTextField3.getText() + "',st_as_desc5='" + jTextField4.getText()  +  "' WHERE st_fullname='" + txtsearch.getText() + "' AND st_grade = '"+jComboBox1.getSelectedItem()+"' AND st_class = '"+jComboBox2.getSelectedItem()+"' ";
                pst = con.prepareStatement(sql);
                pst.execute();
                
                JOptionPane.showMessageDialog(null, "Added Successfully");
              
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Adding Failed");
            }
        }
        
        else if(jComboBox3.getSelectedItem()=="6"){
         try {
                 
                String sql = "UPDATE student_all set st_as_6='" + jComboBox3.getSelectedItem() + "',st_as_name6='" + jTextField5.getText() + "',st_as_marks6='" + jTextField3.getText() + "',st_as_desc6='" + jTextField4.getText()  +  "' WHERE st_fullname='" + txtsearch.getText() + "' AND st_grade = '"+jComboBox1.getSelectedItem()+"' AND st_class = '"+jComboBox2.getSelectedItem()+"' ";
                pst = con.prepareStatement(sql);
                pst.execute();
                
                JOptionPane.showMessageDialog(null, "Added Successfully");
              
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Adding Failed");
            }
        }
        
        else {
             JOptionPane.showMessageDialog(null, "Please Select Correct Assessment Number");
        }
         table();
        databaseNama();
        databaseNamas();
        databaseNama1();
        databaseNamas1();
         reset();
          }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtsearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyPressed
         switch(evt.getKeyCode()) {
            case KeyEvent.VK_BACK_SPACE:
            search.setEnabled(false);
            jButton2.setVisible(false);
            jButton1.setVisible(true);
            jButton3.setEnabled(false);
            jTextField3.setText("");
            jTextField2.setText("");
            jTextField1.setText("");
            txtsearch.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jComboBox3.setSelectedIndex(0);
            jComboBox1.setSelectedIndex(0);
            jComboBox2.setSelectedIndex(0);  
            break;
            case KeyEvent.VK_ENTER:
            txtsearch.setText(txtsearch.getText());
            search.setEnabled(true);
            jButton2.setVisible(true);
            jButton1.setVisible(false);
            jButton3.setEnabled(false);
            try {
            
             Connection conn = db.connect();
               Statement s = conn.createStatement();
             
            rs = s.executeQuery("SELECT * FROM student_all WHERE st_fullname='" + txtsearch.getText() + "'");
            while (rs.next()) {

                jTextField1.setText(rs.getString("st_fname"));
                jTextField6.setText(rs.getString("st_mname"));
                jTextField2.setText(rs.getString("st_lname"));
                jComboBox1.setSelectedItem(rs.getString("st_grade"));
                jComboBox2.setSelectedItem(rs.getString("st_class"));
                
         }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Name");
            
        }        
                
            break;
            default:
            EventQueue.invokeLater(new Runnable(){
                @Override

            
            public void run() {
            String txt = txtsearch.getText();
            autoComplete(txt);
            }
            });
        }
    }//GEN-LAST:event_txtsearchKeyPressed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
 switch(evt.getKeyCode()) {
            case KeyEvent.VK_BACK_SPACE:
            search.setEnabled(false);
            jButton2.setVisible(false);
            jButton1.setVisible(true);
            jButton3.setEnabled(false);
            jTextField3.setText("");
            jTextField2.setText("");
            jTextField1.setText("");
            txtsearch.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jComboBox3.setSelectedIndex(0);
            jComboBox1.setSelectedIndex(0);
            jComboBox2.setSelectedIndex(0);  
            break;
            case KeyEvent.VK_ENTER:
            txtsearch.setText(txtsearch.getText());
            search.setEnabled(false);
            jButton2.setVisible(true);
            jButton1.setVisible(false);
            jButton3.setEnabled(true);
            try {
            
             Connection conn = db.connect();
               Statement s = conn.createStatement();
             
            rs = s.executeQuery("SELECT * FROM student_all WHERE st_fname='" + jTextField1.getText() + "'");
            while (rs.next()) {

                jTextField6.setText(rs.getString("st_mname"));
                jTextField2.setText(rs.getString("st_lname"));
                jComboBox1.setSelectedItem(rs.getString("st_grade"));
                jComboBox2.setSelectedItem(rs.getString("st_class"));
                
         }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Name");
            
        }        
                
            break;
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
        switch(evt.getKeyCode()) {
            case KeyEvent.VK_BACK_SPACE:
            break;
            case KeyEvent.VK_ENTER:
            jTextField6.setText(jTextField6.getText());
            break;
            default:
            EventQueue.invokeLater(new Runnable(){
                @Override

            
            public void run() {
            String txt = jTextField6.getText();
            autoComplete1(txt);
            }
            });
        }
    }//GEN-LAST:event_jTextField6KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        switch(evt.getKeyCode()) {
            case KeyEvent.VK_BACK_SPACE:
            break;
            case KeyEvent.VK_ENTER:
            jTextField2.setText(jTextField2.getText());
            break;
            default:
            EventQueue.invokeLater(new Runnable(){
                @Override

            
            public void run() {
            String txt = jTextField2.getText();
            autoCompletes1(txt);
            }
            });
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped


        char vchar = evt.getKeyChar();
        if(!(Character.isDigit(vchar))||(vchar == KeyEvent.VK_BACK_SPACE)||(vchar == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
        
        jButton2.setVisible(true);
        search.setEnabled(true);
        jButton1.setVisible(true);
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked

         jButton2.setVisible(true);
        search.setEnabled(true);
        jButton1.setVisible(false);
        
        try {
            int row = jTable2.getSelectedRow();
            String Table_click = (jTable2.getModel().getValueAt(row,0).toString());
            String SQL = "SELECT * FROM student_all WHERE st_fname='" + Table_click + "'";
            pst = con.prepareStatement(SQL);
            rs = pst.executeQuery();
            while (rs.next()) {

                jTextField1.setText(rs.getString("st_fname"));
                jTextField6.setText(rs.getString("st_mname"));
                jTextField2.setText(rs.getString("st_lname"));
                jComboBox1.setSelectedItem(rs.getString("st_grade"));
                jComboBox2.setSelectedItem(rs.getString("st_class"));
                txtsearch.setText(rs.getString("st_fullname"));
                
         }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Name");
            
        }        
    }//GEN-LAST:event_jTable2MouseClicked

    private void txtsearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyTyped
  
        
    }//GEN-LAST:event_txtsearchKeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        jButton2.setVisible(true);
        search.setEnabled(true);
        jButton1.setVisible(true);
        
    }//GEN-LAST:event_jTextField5KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JButton search;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
 private void databaseNama() {
        try {
           Connection conn = db.connect();
           Statement s = conn.createStatement();
           
           String sql = "SELECT * FROM student_all ORDER BY st_fullname ASC";
           rs = s.executeQuery(sql);
           while(rs.next()) {
               String Name = rs.getString("st_fullname");
               name.add(Name);
           }
           
           rs.close();
           s.close();
           conn.close();
           
        } catch (Exception e) {
            
        }
    }
    
    public void autoComplete (String txt) {
        String complete = "";
        int start = txt.length();
        int last = txt.length();
        int a;
        for (a=0; a<name.size(); a++) {
            if(name.get(a).toString().startsWith(txt)) {
              complete = name.get(a).toString();
              last = complete.length();
              break;
            }
        }
        if(last>start) {
            txtsearch.setText(complete);
            txtsearch.setCaretPosition(last);
            txtsearch.moveCaretPosition(start);
        }
    }
    
    // -------------
    
    private void databaseNamas() {
        try {
           Connection conn = db.connect();
           Statement s = conn.createStatement();
           
           String sql = "SELECT * FROM student_all ORDER BY st_fname ASC";
           rs = s.executeQuery(sql);
           while(rs.next()) {
               String Name = rs.getString("st_fname");
               names.add(Name);
           }
           
           rs.close();
           s.close();
           conn.close();
           
        } catch (Exception e) {
            
        }
    }
    
    public void autoCompletes (String txt) {
        String complete = "";
        int start = txt.length();
        int last = txt.length();
        int a;
        for (a=0; a<names.size(); a++) {
            if(names.get(a).toString().startsWith(txt)) {
              complete = names.get(a).toString();
              last = complete.length();
              break;
            }
        }
        if(last>start) {
            jTextField1.setText(complete);
            jTextField1.setCaretPosition(last);
            jTextField1.moveCaretPosition(start);
        }
    }
    
    // -------------
    
    private void databaseNama1() {
        try {
           Connection conn = db.connect();
           Statement s = conn.createStatement();
           
           String sql = "SELECT * FROM student_all"; // WHERE st_fname = '" + jTextField1.getText() + "' ORDER BY st_mname ASC";
           rs = s.executeQuery(sql);
           while(rs.next()) {
               String Name = rs.getString("st_mname");
               name1.add(Name);
           }
           
           rs.close();
           s.close();
           conn.close();
           
        } catch (Exception e) {
            
        }
    }
    
    public void autoComplete1 (String txt) {
        String complete = "";
        int start = txt.length();
        int last = txt.length();
        int a;
        for (a=0; a<name1.size(); a++) {
            if(name1.get(a).toString().startsWith(txt)) {
              complete = name1.get(a).toString();
              last = complete.length();
              break;
            }
        }
        if(last>start) {
            jTextField6.setText(complete);
            jTextField6.setCaretPosition(last);
            jTextField6.moveCaretPosition(start);
        }
    }
    
     // -------------
    
    private void databaseNamas1() {
        try {
           Connection conn = db.connect();
           Statement s = conn.createStatement();
           
           String sql = "SELECT * FROM student_all";
           rs = s.executeQuery(sql);
           while(rs.next()) {
               String Name = rs.getString("st_lname");
               names1.add(Name);
           }
           
           rs.close();
           s.close();
           conn.close();
           
        } catch (Exception e) {
            
        }
    }
    
    public void autoCompletes1 (String txt) {
        String complete = "";
        int start = txt.length();
        int last = txt.length();
        int a;
        for (a=0; a<names1.size(); a++) {
            if(names1.get(a).toString().startsWith(txt)) {
              complete = names1.get(a).toString();
              last = complete.length();
              break;
            }
        }
        if(last>start) {
            jTextField2.setText(complete);
            jTextField2.setCaretPosition(last);
            jTextField2.moveCaretPosition(start);
        }
    }
    
    
}
