/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author tj.rumesh
 */
public class regist extends javax.swing.JFrame {
String usr;
String re;
Connection con= null;
ResultSet rs=null;
PreparedStatement pst=null;
// private static regist obj=null;
    /**
     * Creates new form regist
     */
    private regist() {
        initComponents();
        
    }
//public static regist getObj(){
//    if(obj == null) {
//        obj = new regist();
//    }
//    return obj;
//}
    regist(String user) {
            initComponents();
            con = db.connect();
            usr = user;
             try {
            
             Connection conn = db.connect();
             Statement s = conn.createStatement();
             
            rs = s.executeQuery("SELECT * FROM profile WHERE un='" + usr + "'");
            while (rs.next()) {

                jTextField1.setText(rs.getString("fname"));
                jTextField3.setText(rs.getString("nic"));
                jTextField2.setText(rs.getString("lname"));
                jComboBox1.setSelectedItem(rs.getString("gender"));
                jTextField4.setText(rs.getString("email"));
                jTextField5.setText(rs.getString("mobile"));
                jTextArea1.setText(rs.getString("address"));
                
         }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Name");
            
        }        
          
           // jLabel5.setText(user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(530, 180, 400, 160));
        setMaximumSize(new java.awt.Dimension(400, 160));
        setMinimumSize(new java.awt.Dimension(400, 160));
        setUndecorated(true);

        jPanel1.setMaximumSize(new java.awt.Dimension(400, 163));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 163));
        jPanel1.setLayout(null);

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(360, 0, 40, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("First Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 40, 120, 30);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(160, 40, 220, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Last Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 80, 120, 30);

        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField2);
        jTextField2.setBounds(160, 80, 220, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Gender");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 120, 110, 30);

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(160, 120, 220, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("NIC Number");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 160, 120, 30);

        jTextField3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField3);
        jTextField3.setBounds(160, 160, 220, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("School Address");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 260, 120, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextArea1.setSelectedTextColor(new java.awt.Color(255, 153, 0));
        jTextArea1.setSelectionColor(new java.awt.Color(0, 51, 0));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(160, 240, 220, 78);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("School Name");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 200, 100, 30);

        jTextField4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField4);
        jTextField4.setBounds(160, 200, 220, 30);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Mobile No");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 330, 130, 30);

        jTextField5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(160, 330, 220, 30);

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Update Profile");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(160, 380, 220, 30);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        char vchar = evt.getKeyChar();
        if(!(Character.isDigit(vchar))||(vchar == KeyEvent.VK_BACK_SPACE)||(vchar == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         // Fname validations
        String name1 = jTextField1.getText();
        int count_Fname = 0;
        boolean Fname = false;

        if (name1.length() == 0) {
            jTextField1.setBackground(Color.GREEN);
        }
        
        for (int i = 0; i < name1.length(); i++) {
            if (Character.isLetter(name1.charAt(i))) {
                count_Fname++;
            }
        }
        if (count_Fname == name1.length()) {
            Fname = true;
            System.out.println("error in true");
        } else {
    //         jTextField1.setCaretColor(Color.red); // cursor
    //         jTextField1.setBackground(Color.red); // background
               jTextField1.setForeground(Color.red); // foreground
        }

        // end of Fname validations
        
                // Lname validations
        String name2 = jTextField2.getText();
        int count_Lname = 0;
        boolean Lname = false;

        if (name2.length() == 0) {
            jTextField2.setBackground(Color.GREEN);
        }
        
        for (int i = 0; i < name2.length(); i++) {
            if (Character.isLetter(name2.charAt(i))) {
                count_Lname++;
            }
        }
        if (count_Lname == name2.length()) {
            Lname = true;
            System.out.println("error in true");
        } else {
    //         jTextField1.setCaretColor(Color.red); // cursor
    //         jTextField1.setBackground(Color.red); // background
               jTextField2.setForeground(Color.red); // foreground
        }

        // end of Lname validations
        
         //Tel Validation
        String ph = jTextField5.getText();
        int count_Phone = 0;
        boolean Phn = false;
        if (ph.length()==10) {
            for (int i = 0; i < ph.length(); i++) {
                if (Character.isDigit(ph.charAt(i))) {
                    count_Phone++;
                }
            }
            if (count_Phone == ph.length()) {
                Phn = true;
            } else {
                jTextField5.setForeground(Color.red);
            }
        } else if (ph.length() == 0) {
            jTextField5.setBackground(Color.GREEN);
        } else {
            jTextField5.setForeground(Color.red);
        }

        // end of TP Validation

         //NIC Validation         
        boolean getCount = false;
        boolean letter = false;
        int count = 0;
        boolean NIC = false;

        String nic = jTextField3.getText();
        if (nic.length() == 10) {
            String dig = nic.substring(0, 8);
            for (int i = 0; i < dig.length(); i++) {
                if (Character.isDigit(dig.charAt(i))) {
                    count++;
                }
            }
            if (count != dig.length()) {
                jTextField3.setForeground(Color.red);
            } else {
                getCount = true;
            }
            if (nic.charAt(9) == 'V' || nic.charAt(9) == 'v') {
                letter = true;
            } else {
               jTextField3.setForeground(Color.red);
            }
            if (getCount == true && letter == true) {
                NIC = true;
            } else {
               jTextField3.setForeground(Color.red);
            }
        } else if (nic.length() == 0) {
           jTextField3.setBackground(Color.GREEN);
        } else {
            jTextField3.setForeground(Color.red);
        }

       //  end of NIC Validation
       
    if(Fname == true && name1.length() != 0 && Lname == true && name2.length() != 0 && NIC == true && nic.length() != 0) {
        try {
                String sql1 = "UPDATE profile set fname = '" + jTextField1.getText() + "',lname = '" + jTextField2.getText() + "',gender = '" + jComboBox1.getSelectedItem() + "',nic = '" + jTextField3.getText() + "',address = '" + jTextArea1.getText() +"',email = '" + jTextField4.getText()  +"',mobile = '" + jTextField5.getText() +"'  WHERE un = '" + usr + "'";            
                pst = con.prepareStatement(sql1);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Profile Updated Successfully");
//                resets();
           
            } catch (Exception e) {
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "Profile Update Failed, Try Again !");
            } 
       }            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER) {
        // Fname validations
        String name1 = jTextField1.getText();
        int count_Fname = 0;
        boolean Fname = false;

        if (name1.length() == 0) {
            jTextField1.setBackground(Color.GREEN);
        }
        
        for (int i = 0; i < name1.length(); i++) {
            if (Character.isLetter(name1.charAt(i))) {
                count_Fname++;
            }
        }
        if (count_Fname == name1.length()) {
            Fname = true;
            System.out.println("error in true");
        } else {
    //         jTextField1.setCaretColor(Color.red); // cursor
    //         jTextField1.setBackground(Color.red); // background
               jTextField1.setForeground(Color.red); // foreground
        }

        // end of Fname validations
        
                // Lname validations
        String name2 = jTextField2.getText();
        int count_Lname = 0;
        boolean Lname = false;

        if (name2.length() == 0) {
            jTextField2.setBackground(Color.GREEN);
        }
        
        for (int i = 0; i < name2.length(); i++) {
            if (Character.isLetter(name2.charAt(i))) {
                count_Lname++;
            }
        }
        if (count_Lname == name2.length()) {
            Lname = true;
            System.out.println("error in true");
        } else {
    //         jTextField1.setCaretColor(Color.red); // cursor
    //         jTextField1.setBackground(Color.red); // background
               jTextField2.setForeground(Color.red); // foreground
        }

        // end of Lname validations
        
         //Tel Validation
        String ph = jTextField5.getText();
        int count_Phone = 0;
        boolean Phn = false;
        if (ph.length()==10) {
            for (int i = 0; i < ph.length(); i++) {
                if (Character.isDigit(ph.charAt(i))) {
                    count_Phone++;
                }
            }
            if (count_Phone == ph.length()) {
                Phn = true;
            } else {
                jTextField5.setForeground(Color.red);
            }
        } else if (ph.length() == 0) {
            jTextField5.setBackground(Color.GREEN);
        } else {
            jTextField5.setForeground(Color.red);
        }

        // end of TP Validation

         //NIC Validation         
        boolean getCount = false;
        boolean letter = false;
        int count = 0;
        boolean NIC = false;

        String nic = jTextField3.getText();
        if (nic.length() == 10) {
            String dig = nic.substring(0, 8);
            for (int i = 0; i < dig.length(); i++) {
                if (Character.isDigit(dig.charAt(i))) {
                    count++;
                }
            }
            if (count != dig.length()) {
                jTextField3.setForeground(Color.red);
            } else {
                getCount = true;
            }
            if (nic.charAt(9) == 'V' || nic.charAt(9) == 'v') {
                letter = true;
            } else {
               jTextField3.setForeground(Color.red);
            }
            if (getCount == true && letter == true) {
                NIC = true;
            } else {
               jTextField3.setForeground(Color.red);
            }
        } else if (nic.length() == 0) {
           jTextField3.setBackground(Color.GREEN);
        } else {
            jTextField3.setForeground(Color.red);
        }

       //  end of NIC Validation
       
    if(Fname == true && name1.length() != 0 && Lname == true && name2.length() != 0 && NIC == true && nic.length() != 0) {
        try {
                String sql1 = "UPDATE profile set fname = '" + jTextField1.getText() + "',lname = '" + jTextField2.getText() + "',gender = '" + jComboBox1.getSelectedItem() + "',nic = '" + jTextField3.getText() + "',address = '" + jTextArea1.getText() +"',email = '" + jTextField4.getText()  +"',mobile = '" + jTextField5.getText() +"'  WHERE un = '" + usr + "'";            
                pst = con.prepareStatement(sql1);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Profile Updated Successfully");
  
           
            } catch (Exception e) {
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "Profile Update Failed, Try Again !");
            } 
    }     
    }//GEN-LAST:event_jTextField5KeyPressed
    }
     public void resets(){

        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextArea1.setText("");
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
