/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school;

import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author tj.rumesh
 */
public class repo extends javax.swing.JInternalFrame {
Connection con= null;
ResultSet rs=null;
PreparedStatement pst=null;
String usr;
    /**
     * Creates new form repo
     */
    public repo() {
        initComponents();
        con = db.connect();
    }

    repo(String user) {
        initComponents();
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jComboBox2.setVisible(true);
        jComboBox3.setVisible(true);
        usr = user;
        con = db.connect();
        try {
            
             Connection conn = db.connect();
               Statement s = conn.createStatement();
             
            rs = s.executeQuery("SELECT * FROM profile WHERE un='" + usr + "'");
            while (rs.next()) {

                String fname = rs.getString("fname");
                String lname = rs.getString("lname");
                
                String fullname = fname +" "+ lname;
                
                jLabel8.setText(fullname);
                jLabel9.setText(rs.getString("email"));
                jLabel10.setText(rs.getString("address"));
                
         }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Username");
            
        }       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setEnabled(false);
        setMinimumSize(new java.awt.Dimension(593, 393));
        setNormalBounds(new java.awt.Rectangle(150, 180, 0, 0));

        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("View Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(240, 300, 260, 23);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Teacher Name ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 90, 130, 14);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("School Address");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 150, 120, 14);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Report Category");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 190, 110, 14);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Subject");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 230, 110, 14);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Student Index No");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 270, 110, 14);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("School Name");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 120, 90, 14);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(240, 90, 260, 17);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(240, 120, 260, 17);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 51));
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(240, 150, 260, 17);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Class Report", "Student Report" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(240, 180, 260, 30);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 51));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(240, 220, 260, 30);

        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 0, 51));
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(240, 260, 260, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("REPORT VIEWER");
        jLabel11.setToolTipText("");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(110, 20, 370, 40);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(240, 220, 260, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B" }));
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(240, 260, 260, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/repo.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 580, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        String report="";
        String repoCat = jComboBox1.getSelectedItem().toString();
        
        String indx=jTextField2.getText();
        String sub=jTextField1.getText();
        String scl_name = jLabel9.getText();
        String scl_address = jLabel10.getText();
        String teacher=jLabel8.getText();
        String grade = jComboBox2.getSelectedItem().toString();
        String classes = jComboBox3.getSelectedItem().toString();
 
  try {
                    Map param = new HashMap();
                    param.put("p_index", indx);
                    param.put("p_scl_name", scl_name);
                    param.put("p_scl_address", scl_address);
                    param.put("p_subject", sub);
                    param.put("p_teacher", teacher);
                    param.put("p_grade", grade);
                    param.put("p_class", classes);

                    con = db.connect();
                
                    if(repoCat.equals("Student Report")){
                        System.out.println("1");
                        report = "F:\\school\\src\\Reports\\student.jasper";
                        System.out.println("2");
                    }
                    else if(repoCat.equals("Class Report")){
                        report = "F:\\school\\src\\Reports\\class.jasper";
                    }

                    JasperPrint jp = null;
                    jp = JasperFillManager.fillReport(report, param, con);
                    System.out.println(jp);

                    JasperViewer.viewReport(jp, false);

                } catch(Exception ex){

                }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if(jComboBox1.getSelectedItem().toString()=="Student Report"){
            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
            jComboBox2.setVisible(false);
            jComboBox3.setVisible(false);
            jLabel5.setText("Subject");
            jLabel6.setText("Student Index No");
        }
        else if(jComboBox1.getSelectedItem().toString()=="Class Report"){
            jTextField1.setVisible(false);
            jTextField2.setVisible(false);
            jComboBox2.setVisible(true);
            jComboBox3.setVisible(true);
            jLabel5.setText("Grade");
            jLabel6.setText("Class");
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
          if(evt.getKeyCode()==KeyEvent.VK_ENTER) {
               String report="";
        String repoCat = jComboBox1.getSelectedItem().toString();
        
        String indx=jTextField2.getText();
        String sub=jTextField1.getText();
        String scl_name = jLabel9.getText();
        String scl_address = jLabel10.getText();
        String teacher=jLabel8.getText();
        String grade = jComboBox2.getSelectedItem().toString();
        String classes = jComboBox3.getSelectedItem().toString();
 
  try {
                    Map param = new HashMap();
                    param.put("p_index", indx);
                    param.put("p_scl_name", scl_name);
                    param.put("p_scl_address", scl_address);
                    param.put("p_subject", sub);
                    param.put("p_teacher", teacher);
                    param.put("p_grade", grade);
                    param.put("p_class", classes);

                    con = db.connect();
                
                    if(repoCat.equals("Student Report")){
                        System.out.println("1");
                        report = "F:\\school\\src\\Reports\\student.jasper";
                        System.out.println("2");
                    }
                    else if(repoCat.equals("Class Report")){
                        report = "F:\\school\\src\\Reports\\class.jasper";
                    }

                    JasperPrint jp = null;
                    jp = JasperFillManager.fillReport(report, param, con);
                    System.out.println(jp);

                    JasperViewer.viewReport(jp, false);

                } catch(Exception ex){

                }

          }
    }//GEN-LAST:event_jTextField2KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
