/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.EventQueue;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Tharaka Rumesh Jee
 */
public class student extends javax.swing.JInternalFrame {
    Connection con= null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    ArrayList name1 = new ArrayList();
    /**
     * Creates new form student
     */
    public student() {
        initComponents();
        con = db.connect();
        databaseNama1();
        jButton1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(255, 255, 255));
        setFrameIcon(null);
        setMaximumSize(new java.awt.Dimension(928, 560));
        setMinimumSize(new java.awt.Dimension(928, 34));
        setPreferredSize(new java.awt.Dimension(1073, 597));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 0));
        jLabel1.setText("Student Records");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        jLabel2.setText("Index No");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(11, 11, 11))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        jLabel3.setText("Index No");

        jLabel4.setText("Last Name");

        jLabel5.setText("Grade");

        jLabel6.setText("Class");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jLabel11.setText("Gender");

        jLabel12.setText("Evoluation");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(155, 155, 155)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(181, 181, 181)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(11, 11, 11))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        jLabel15.setText("Assessment 01");

        jLabel16.setText("Assessment 02");

        jLabel17.setText("Assessment 03");

        jLabel18.setText("Assessment 04");

        jLabel19.setText("Assessment 05");

        jLabel20.setText("Assessment 06");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel27.setText("Average");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel24))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel27))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(39, 39, 39))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel21))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel22))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel23))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel24))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel25))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel26))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        jLabel29.setText("Term Test 01");

        jLabel30.setText("Term Test 02");

        jLabel31.setText("Term Test 03");

        jLabel32.setText("Total");

        jLabel33.setText("Average");

        jLabel34.setText("Overall Marks");

        jLabel35.setText("Overall Average");

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(204, 0, 0));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(204, 0, 0));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(204, 0, 0));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(204, 0, 0));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel42.setPreferredSize(new java.awt.Dimension(48, 14));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(jLabel34)
                    .addComponent(jLabel33)
                    .addComponent(jLabel32)
                    .addComponent(jLabel31)
                    .addComponent(jLabel30)
                    .addComponent(jLabel29))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41)
                    .addComponent(jLabel40)
                    .addComponent(jLabel39)
                    .addComponent(jLabel38)
                    .addComponent(jLabel37)
                    .addComponent(jLabel36))
                .addGap(31, 31, 31))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel41))
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel40))
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel39))
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jLabel38))
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel37))
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36))
                .addGap(11, 11, 11))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(398, 120));
        jPanel9.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(267, 267, 267)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jButton1.setEnabled(true);
        try {
            
             Connection conn = db.connect();
               Statement s = conn.createStatement();
             
            rs = s.executeQuery("SELECT * FROM student_all WHERE st_fname='" + jTextField1.getText() + "'");
            while (rs.next()) {

                jLabel7.setText(rs.getString("st_fname"));
                jLabel8.setText(rs.getString("st_lname"));
                jLabel9.setText(rs.getString("st_grade"));
                jLabel10.setText(rs.getString("st_class"));
                jLabel14.setText(rs.getString("st_gender"));
                
                jLabel21.setText(rs.getString("st_as_marks1"));
                jLabel22.setText(rs.getString("st_as_marks2"));
                jLabel23.setText(rs.getString("st_as_marks3"));
                jLabel24.setText(rs.getString("st_as_marks4"));
                jLabel25.setText(rs.getString("st_as_marks5"));
                jLabel26.setText(rs.getString("st_as_marks6"));
                
                jLabel42.setText(rs.getString("st_se_marks1"));
                jLabel41.setText(rs.getString("st_se_marks2"));
                jLabel40.setText(rs.getString("st_se_marks3"));
                  
                String a = jLabel40.getText();
                int b = Integer.parseInt(a);
                
                
                String a1 = jLabel41.getText();
                int b1 = Integer.parseInt(a1);
                
                
                String a2 = jLabel42.getText();
                int b2 = Integer.parseInt(a2);
               
                
                // assessment 
                String a3 = jLabel21.getText();
                int b3 = Integer.parseInt(a3);
                
                
                String a4 = jLabel22.getText();
                int b4 = Integer.parseInt(a4);
               
                
                String a5 = jLabel23.getText();
                int b5 = Integer.parseInt(a5);
             
                
                String a6 = jLabel24.getText();
                int b6 = Integer.parseInt(a6);
               
                
                String a7 = jLabel25.getText();
                int b7 = Integer.parseInt(a7);
               
                
                String a8 = jLabel26.getText();
                int b8 = Integer.parseInt(a8);
               
                // end assessment
              
                
                int []arr = {b,b1,b2};
            
                int count2 = 0;
                int count3 = 0;
           
                for(int i=0 ; i < arr.length ; i++) {
                    if (arr[i]==0) {
                        count3++;
                    
                }
                    else {
                    count2++;
                    }
                 
                    
                }
                // new added
                int tot = b+b1+b2;
                String tot1 = String.valueOf(tot);
                jLabel39.setText(tot1);
                System.out.println("total " + tot);
                
                if (count2 == 0) {
                    jLabel38.setText("not yet");
                    
                    // ----------------------------------------------------------------------------------------
                    
                     int []array = {b3,b4,b5,b6,b7,b8};
                int count1 = 0;
                int count4 = 0;
                
                for(int j=0 ; j < array.length ; j++) {
                    if (array[j]==0) {
                   count4++;
                         
                }
                    else {
                    count1++;
                        
                    }
            
                }
               
                int tot2 = b3+b4+b5+b6+b7+b8;
                int tot3 = tot + tot2;
                String tot4 = String.valueOf(tot3);
                jLabel37.setText(tot4);
                
                // new added 1
                
                if (count1==0) {
                 jLabel28.setText("not yet"); 
                 jLabel36.setText("not yet");
                 jLabel13.setText(" not yet ");    
                 
                }
                
                else {
                int avg2 = (b3+b4+b5+b6+b7+b8)/count1;
                
                String avg3 = String.valueOf(avg2);
                
                jLabel28.setText(avg3 + " %");
                jLabel36.setText(avg3 + " %");
                
                 if (avg2 >= 80) {
                jLabel13.setText(" Very Good ");    
                }
                
                else if ((avg2 < 80) && (avg2 >= 60 ) ) {
                jLabel13.setText(" Good ");    
                }
                
                else if ((avg2 < 60) && (avg2 >= 40 ) ) {
                jLabel13.setText(" Medium ");    
                }
                
                else if ((avg2 < 40) && (avg2 >= 20 ) ) {
                jLabel13.setText(" Weak ");    
                }
                
                else if ((avg2 < 20) && (avg2 >= 0 ) ) {
                jLabel13.setText(" Very Weak ");    
                }
                
                else {
                jLabel13.setText(" Wrong Inputs ");     
                } 
                 
                // end assessment

                }
                // end new added 1
                    
               
                    
                    // ----------------------------------------------------------------------------------------
                    
                }
                
                else {
                int avg = (b+b1+b2)/count2;
                System.out.println("avg " + avg);
         
                String avg1 = String.valueOf(avg);
               
                jLabel38.setText(avg1 + " %");
                
                // ------------------------------------------------------------
                 int []array = {b3,b4,b5,b6,b7,b8};
                int count1 = 0;
                int count4 = 0;
                
                for(int j=0 ; j < array.length ; j++) {
                    if (array[j]==0) {
                   count4++;
                         
                }
                    else {
                    count1++;
                        
                    }
            
                }
               
                int tot2 = b3+b4+b5+b6+b7+b8;
                int tot3 = tot + tot2;
                String tot4 = String.valueOf(tot3);
                jLabel37.setText(tot4);
                
                // new added 1
                
                if (count1==0) {
                 jLabel28.setText("not yet");   
                 jLabel36.setText(avg + " %");
                 
                 if (avg >= 80) {
                jLabel13.setText(" Very Good ");    
                }
                
                else if ((avg < 80) && (avg >= 60 ) ) {
                jLabel13.setText(" Good ");    
                }
                
                else if ((avg < 60) && (avg >= 40 ) ) {
                jLabel13.setText(" Medium ");    
                }
                
                else if ((avg < 40) && (avg >= 20 ) ) {
                jLabel13.setText(" Weak ");    
                }
                
                else if ((avg < 20) && (avg >= 0 ) ) {
                jLabel13.setText(" Very Weak ");    
                }
                
                else {
                jLabel13.setText(" Wrong Inputs ");     
                }
                 
                }
                
                else {
                int avg2 = (b3+b4+b5+b6+b7+b8)/count1;
                
                String avg3 = String.valueOf(avg2);
                
                jLabel28.setText(avg3 + " %");
                int avg4 = (avg2 + avg)/2;
                String avg5 = String.valueOf(avg4);
                
                jLabel36.setText(avg5 + " %");
                
                // end assessment
                 if (avg4 >= 80) {
                jLabel13.setText(" Very Good ");    
                }
                
                else if ((avg4 < 80) && (avg4 >= 60 ) ) {
                jLabel13.setText(" Good ");    
                }
                
                else if ((avg4 < 60) && (avg4 >= 40 ) ) {
                jLabel13.setText(" Medium ");    
                }
                
                else if ((avg4 < 40) && (avg4 >= 20 ) ) {
                jLabel13.setText(" Weak ");    
                }
                
                else if ((avg4 < 20) && (avg4 >= 0 ) ) {
                jLabel13.setText(" Very Weak ");    
                }
                
                else {
                jLabel13.setText(" Wrong Inputs ");     
                } 
                }
                // end new added 1
 
                // ------------------------------------------------------------
                
                }
                
                // end new added
                // assessment
                 
               
                 
                if (b == 0) {
                   jLabel40.setText("ab"); 
                }
                if (b1 == 0) {
                   jLabel41.setText("ab"); 
                }
                if (b2 == 0) {
                   jLabel42.setText("ab"); 
                }
                if (b3 == 0) {
                   jLabel21.setText("ab"); 
                }
                if (b4 == 0) {
                   jLabel22.setText("ab"); 
                }
                if (b5 == 0) {
                   jLabel23.setText("ab"); 
                }
                if (b6 == 0) {
                   jLabel24.setText("ab"); 
                }
                if (b7 == 0) {
                   jLabel25.setText("ab"); 
                }
                if (b8 == 0) {
                   jLabel26.setText("ab"); 
                }
                
                // ---- charts ----
             
             DefaultCategoryDataset dataset = new DefaultCategoryDataset();
             dataset.setValue(b3,"","As.1");
             dataset.setValue(b4,"","As.2");
             dataset.setValue(b5,"","As.3");
             dataset.setValue(b6,"","As.4");
             dataset.setValue(b7,"","As.5");
             dataset.setValue(b8,"","As.6");
             dataset.setValue(b2,"","Se.1");
             dataset.setValue(b1,"","Se.2");
             dataset.setValue(b,"","Se.3");
             
             JFreeChart chart = ChartFactory.createBarChart("Student Records","","Marks Average (%)", dataset,PlotOrientation.HORIZONTAL, false,false,false);
             CategoryPlot catPlot = chart.getCategoryPlot();
             catPlot.setRangeGridlinePaint(Color.BLACK);
             
             ChartPanel chartPanel = new ChartPanel(chart);
             jPanel8.removeAll();
             jPanel8.add(chartPanel,BorderLayout.CENTER);
             jPanel8.validate();
             
             // ---- end charts ----
             
            // ---- charts ----
             
             DefaultCategoryDataset datasets = new DefaultCategoryDataset();
             datasets.setValue(b3,"","As.1");
             datasets.setValue(b4,"","As.2");
             datasets.setValue(b5,"","As.3");
             datasets.setValue(b6,"","As.4");
             datasets.setValue(b7,"","As.5");
             datasets.setValue(b8,"","As.6");
             datasets.setValue(b2,"","Se.1");
             datasets.setValue(b1,"","Se.2");
             datasets.setValue(b,"","Se.3");
             
             JFreeChart charts = ChartFactory.createLineChart("Student Records", "", "", datasets);
             CategoryPlot catPlots = charts.getCategoryPlot();
             catPlots.setRangeGridlinePaint(Color.BLACK);
             
             ChartPanel chartPanels = new ChartPanel(charts);
             jPanel9.removeAll();
             jPanel9.add(chartPanels,BorderLayout.CENTER);
             jPanel9.validate();
             
             // ---- end charts ----
             
                
         }
           
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Name1");
            
        }        
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        switch(evt.getKeyCode()) {
            case KeyEvent.VK_BACK_SPACE:
                
            jButton1.setEnabled(false);
            jLabel7.setText("");
            jLabel8.setText("");
            jLabel9.setText("");
            jLabel10.setText("");
            jLabel13.setText("");
            jLabel14.setText("");
            jTextField1.setText("");
            
           // jLabel20.setText("");
            jLabel21.setText("");
            jLabel22.setText("");
            jLabel23.setText("");
            jLabel24.setText("");
            jLabel25.setText("");
            jLabel26.setText("");
            jLabel28.setText("");
            
            jLabel36.setText("");
            jLabel37.setText("");
            jLabel38.setText("");
            jLabel39.setText("");
            jLabel40.setText("");
            jLabel41.setText("");
            jLabel42.setText("");
                
            break;
            case KeyEvent.VK_ENTER:
            jTextField1.setText(jTextField1.getText());
            jButton1.setEnabled(true);
             try {
            
             Connection conn = db.connect();
               Statement s = conn.createStatement();
             
            rs = s.executeQuery("SELECT * FROM student_all WHERE st_fname='" + jTextField1.getText() + "'");
            while (rs.next()) {

                jLabel7.setText(rs.getString("st_fname"));
                jLabel8.setText(rs.getString("st_lname"));
                jLabel9.setText(rs.getString("st_grade"));
                jLabel10.setText(rs.getString("st_class"));
                jLabel14.setText(rs.getString("st_gender"));
                
                jLabel21.setText(rs.getString("st_as_marks1"));
                jLabel22.setText(rs.getString("st_as_marks2"));
                jLabel23.setText(rs.getString("st_as_marks3"));
                jLabel24.setText(rs.getString("st_as_marks4"));
                jLabel25.setText(rs.getString("st_as_marks5"));
                jLabel26.setText(rs.getString("st_as_marks6"));
                
                jLabel42.setText(rs.getString("st_se_marks1"));
                jLabel41.setText(rs.getString("st_se_marks2"));
                jLabel40.setText(rs.getString("st_se_marks3"));
                
                String a = jLabel40.getText();
                int b = Integer.parseInt(a);
           
                
                String a1 = jLabel41.getText();
                int b1 = Integer.parseInt(a1);
                
                
                String a2 = jLabel42.getText();
                int b2 = Integer.parseInt(a2);
               
                
                // assessment 
                String a3 = jLabel21.getText();
                int b3 = Integer.parseInt(a3);
                
                
                String a4 = jLabel22.getText();
                int b4 = Integer.parseInt(a4);
               
                
                String a5 = jLabel23.getText();
                int b5 = Integer.parseInt(a5);
             
                
                String a6 = jLabel24.getText();
                int b6 = Integer.parseInt(a6);
               
                
                String a7 = jLabel25.getText();
                int b7 = Integer.parseInt(a7);
               
                
                String a8 = jLabel26.getText();
                int b8 = Integer.parseInt(a8);
               
                // end assessment
                
                
                int []arr = {b,b1,b2};
            
                int count2 = 0;
                int count3 = 0;
           
                for(int i=0 ; i < arr.length ; i++) {
                    if (arr[i]==0) {
                        count3++;
                    
                }
                    else {
                    count2++;
                    }
                 
                    
                }
                // new added
                int tot = b+b1+b2;
                String tot1 = String.valueOf(tot);
                jLabel39.setText(tot1);
                System.out.println("total " + tot);
                
                if (count2 == 0) {
                    jLabel38.setText("not yet");
                    
                    // ----------------------------------------------------------------------------------------
                    
                     int []array = {b3,b4,b5,b6,b7,b8};
                int count1 = 0;
                int count4 = 0;
                
                for(int j=0 ; j < array.length ; j++) {
                    if (array[j]==0) {
                   count4++;
                         
                }
                    else {
                    count1++;
                        
                    }
            
                }
               
                int tot2 = b3+b4+b5+b6+b7+b8;
                int tot3 = tot + tot2;
                String tot4 = String.valueOf(tot3);
                jLabel37.setText(tot4);
                
                // new added 1
                
                if (count1==0) {
                 jLabel28.setText("not yet"); 
                 jLabel36.setText("not yet");
                 jLabel13.setText(" not yet ");    
                 
                }
                
                else {
                int avg2 = (b3+b4+b5+b6+b7+b8)/count1;
                
                String avg3 = String.valueOf(avg2);
                
                jLabel28.setText(avg3 + " %");
                jLabel36.setText(avg3 + " %");
                
                 if (avg2 >= 80) {
                jLabel13.setText(" Very Good ");    
                }
                
                else if ((avg2 < 80) && (avg2 >= 60 ) ) {
                jLabel13.setText(" Good ");    
                }
                
                else if ((avg2 < 60) && (avg2 >= 40 ) ) {
                jLabel13.setText(" Medium ");    
                }
                
                else if ((avg2 < 40) && (avg2 >= 20 ) ) {
                jLabel13.setText(" Weak ");    
                }
                
                else if ((avg2 < 20) && (avg2 >= 0 ) ) {
                jLabel13.setText(" Very Weak ");    
                }
                
                else {
                jLabel13.setText(" Wrong Inputs ");     
                } 
                 
                // end assessment

                }
                // end new added 1
                    
               
                    
                    // ----------------------------------------------------------------------------------------
                    
                }
                
                else {
                int avg = (b+b1+b2)/count2;
                System.out.println("avg " + avg);
         
                String avg1 = String.valueOf(avg);
               
                jLabel38.setText(avg1 + " %");
                
                // ------------------------------------------------------------
                 int []array = {b3,b4,b5,b6,b7,b8};
                int count1 = 0;
                int count4 = 0;
                
                for(int j=0 ; j < array.length ; j++) {
                    if (array[j]==0) {
                   count4++;
                         
                }
                    else {
                    count1++;
                        
                    }
            
                }
               
                int tot2 = b3+b4+b5+b6+b7+b8;
                int tot3 = tot + tot2;
                String tot4 = String.valueOf(tot3);
                jLabel37.setText(tot4);
                
                // new added 1
                
                if (count1==0) {
                 jLabel28.setText("not yet");   
                 jLabel36.setText(avg + " %");
                 
                 if (avg >= 80) {
                jLabel13.setText(" Very Good ");    
                }
                
                else if ((avg < 80) && (avg >= 60 ) ) {
                jLabel13.setText(" Good ");    
                }
                
                else if ((avg < 60) && (avg >= 40 ) ) {
                jLabel13.setText(" Medium ");    
                }
                
                else if ((avg < 40) && (avg >= 20 ) ) {
                jLabel13.setText(" Weak ");    
                }
                
                else if ((avg < 20) && (avg >= 0 ) ) {
                jLabel13.setText(" Very Weak ");    
                }
                
                else {
                jLabel13.setText(" Wrong Inputs ");     
                }
                 
                }
                
                else {
                int avg2 = (b3+b4+b5+b6+b7+b8)/count1;
                
                String avg3 = String.valueOf(avg2);
                
                jLabel28.setText(avg3 + " %");
                int avg4 = (avg2 + avg)/2;
                String avg5 = String.valueOf(avg4);
                
                jLabel36.setText(avg5 + " %");
                
                // end assessment
                 if (avg4 >= 80) {
                jLabel13.setText(" Very Good ");    
                }
                
                else if ((avg4 < 80) && (avg4 >= 60 ) ) {
                jLabel13.setText(" Good ");    
                }
                
                else if ((avg4 < 60) && (avg4 >= 40 ) ) {
                jLabel13.setText(" Medium ");    
                }
                
                else if ((avg4 < 40) && (avg4 >= 20 ) ) {
                jLabel13.setText(" Weak ");    
                }
                
                else if ((avg4 < 20) && (avg4 >= 0 ) ) {
                jLabel13.setText(" Very Weak ");    
                }
                
                else {
                jLabel13.setText(" Wrong Inputs ");     
                } 
                }
                // end new added 1
 
                // ------------------------------------------------------------
                
                }
                
                // end new added
                // assessment
                 
               
                 
                if (b == 0) {
                   jLabel40.setText("ab"); 
                }
                if (b1 == 0) {
                   jLabel41.setText("ab"); 
                }
                if (b2 == 0) {
                   jLabel42.setText("ab"); 
                }
                if (b3 == 0) {
                   jLabel21.setText("ab"); 
                }
                if (b4 == 0) {
                   jLabel22.setText("ab"); 
                }
                if (b5 == 0) {
                   jLabel23.setText("ab"); 
                }
                if (b6 == 0) {
                   jLabel24.setText("ab"); 
                }
                if (b7 == 0) {
                   jLabel25.setText("ab"); 
                }
                if (b8 == 0) {
                   jLabel26.setText("ab"); 
                }
                
                 // ---- charts ----
             
             DefaultCategoryDataset dataset = new DefaultCategoryDataset();
             dataset.setValue(b3,"","As.1");
             dataset.setValue(b4,"","As.2");
             dataset.setValue(b5,"","As.3");
             dataset.setValue(b6,"","As.4");
             dataset.setValue(b7,"","As.5");
             dataset.setValue(b8,"","As.6");
             dataset.setValue(b2,"","Se.1");
             dataset.setValue(b1,"","Se.2");
             dataset.setValue(b,"","Se.3");
             
             JFreeChart chart = ChartFactory.createBarChart("Student Records","","Marks Average (%)", dataset,PlotOrientation.HORIZONTAL, false,false,false);
             CategoryPlot catPlot = chart.getCategoryPlot();
             catPlot.setRangeGridlinePaint(Color.BLACK);
             
             ChartPanel chartPanel = new ChartPanel(chart);
             jPanel8.removeAll();
             jPanel8.add(chartPanel,BorderLayout.CENTER);
             jPanel8.validate();
             
             // ---- end charts ----
             
            // ---- charts ----
             
             DefaultCategoryDataset datasets = new DefaultCategoryDataset();
             datasets.setValue(b3,"","As.1");
             datasets.setValue(b4,"","As.2");
             datasets.setValue(b5,"","As.3");
             datasets.setValue(b6,"","As.4");
             datasets.setValue(b7,"","As.5");
             datasets.setValue(b8,"","As.6");
             datasets.setValue(b2,"","Se.1");
             datasets.setValue(b1,"","Se.2");
             datasets.setValue(b,"","Se.3");
             
             JFreeChart charts = ChartFactory.createLineChart("Student Records", "", "", datasets);
             CategoryPlot catPlots = charts.getCategoryPlot();
             catPlots.setRangeGridlinePaint(Color.BLACK);
             
             ChartPanel chartPanels = new ChartPanel(charts);
             jPanel9.removeAll();
             jPanel9.add(chartPanels,BorderLayout.CENTER);
             jPanel9.validate();
             
             // ---- end charts ----
             
                
         }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Name2");
            
        }        
                
            break;
            default:
            EventQueue.invokeLater(new Runnable(){
                @Override

            
            public void run() {
            String txt = jTextField1.getText();
            autoComplete1(txt);
            }
            });
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped

    }//GEN-LAST:event_jTextField1KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
private void databaseNama1() {
        try {
           Connection conn = db.connect();
           Statement s = conn.createStatement();
           
           String sql = "SELECT * FROM student_all ORDER BY st_fname ASC";
           rs = s.executeQuery(sql);
           while(rs.next()) {
               String Name = rs.getString("st_fname");
               name1.add(Name);
           }
           
           rs.close();
           s.close();
           conn.close();
           
        } catch (Exception e) {
            
        }
    }
    
    public void autoComplete1 (String txt) {
        String complete = "";
        int start = txt.length();
        int last = txt.length();
        int a;
        for (a=0; a<name1.size(); a++) {
            if(name1.get(a).toString().startsWith(txt)) {
              complete = name1.get(a).toString();
              last = complete.length();
              break;
            }
        }
        if(last>start) {
            jTextField1.setText(complete);
            jTextField1.setCaretPosition(last);
            jTextField1.moveCaretPosition(start);
        }
    }
    
}
